export const FETCH_COINBASE = "FETCH_COINBASE";
export const FETCH_KRAKEN = "FETCH_KRAKEN";
export const FETCH_COINBASE_REVERSE = "FETCH_COINBASE_REVERSE";
export const FETCH_USD = "FETCH_USD";
export const FETCH_SELECTIONS_REVERSE = "FETCH_SELECTIONS_REVERSE";
export const FETCH_SELECTIONS = "FETCH_SELECTIONS";
